### ISSUE TITLE
How to use set_geometry from Dask DF and export as geopackage?

### ISSUE THREAD

**Issue by Guts** [jsignell/dask-geopandas#16]
First of all, thanks for this work :+1:.

Then, I'm trying to convert a Dask DataFrame into a GeoPandas, setting geometry from 2 columns (x,y) and I think there is a problem in the README instructions:

```python
import dask.dataframe as dd
import dask_geopandas

df = dd.read_csv('...')

df = df.set_geometry(
    dask_geopandas.points_from_xy(df, 'latitude', 'longitude')
)
```

In that case, `df` is a dask dataframe and doesn't have attribute/method like `set_geometry`, raising a : `AttributeError: 'DataFrame' object has no attribute 'set_geometry`.

Digging into the source code, I've finally did:

```python
geodf = dask_geopandas.from_dask_dataframe(df)

geodf = geodf.set_geometry(
    dask_geopandas.points_from_xy(
            df=geodf,
            x=geodf.x,
            y=geodf.y,
        )
)
```

But then, I'm not unable to export it as a geopackage. Am I missing something?

**Comment by mziminski** [comment]
> ```python
> from dask.delayed import delayed, tokenize
> 
> 
> @delayed
> def _extra_deps(func, *args, extras=None, **kwargs):
>     return func(*args, **kwargs)
> 
> 
> def to_file(df, path, driver="GPKG", parallel=False, compute=True, **kwargs):  # replaced "GPKG" with "ESRI Shapefile"
>     """
>     Write to single file.
>     
>     Parameters
>     ----------
>     df : dask_geopandas.GeoDataFrame
>     path : str
>         Filename.
>     parallel : bool, default False
>         When true, have each block append itself to the DB table concurrently. This can result in DB rows being in a
>         different order than the source DataFrame's corresponding rows. When false, load each block into the SQL DB in
>         sequence.
>     compute : bool, default True
>         When true, call dask.compute and perform the load into SQL; otherwise, return a Dask object (or array of
>         per-block objects when parallel=True)
>     
>     """
>     # based on dask.dataframe's to_sql
>     def make_meta(meta):
>         return meta.to_file(path, driver=driver, mode="w", **kwargs)
> 
>     make_meta = delayed(make_meta)
>     meta_task = make_meta(df._meta)
> 
>     # Partitions should always append to the empty file created from `meta` above
>     worker_kwargs = dict(kwargs, driver=driver, mode="a")
> 
>     if parallel:
>         # Perform the meta insert, then one task that inserts all blocks concurrently:
>         result = [
>             _extra_deps(
>                 d.to_file,
>                 path,
>                 extras=meta_task,
>                 **worker_kwargs,
>                 dask_key_name="to_file-%s" % tokenize(d, **worker_kwargs)
>             )
>             for d in df.to_delayed()
>         ]
>     else:
>         # Chain the "meta" insert and each block's insert
>         result = []
>         last = meta_task
>         for d in df.to_delayed():
>             result.append(
>                 _extra_deps(
>                     d.to_file,
>                     path,
>                     extras=last,
>                     **worker_kwargs,
>                     dask_key_name="to_file-%s" % tokenize(d, **worker_kwargs)
>                 )
>             )
>             last = result[-1]
>     result = delayed(result)
> 
>     if compute:
>         dask.compute(result, scheduler="processes")
>     else:
>         return result
> ```
> 
> And then you can use it like this:
> 
> ```python
> to_file(gdf, "test.gpkg")  # replaced .gpkg with .shp
> ```

<br>

I understand this code is most definitely still experimental, so I tried to modify it slightly to work with ESRI Shapefiles (please reference the comments in the above code), but I got these errors for both the gpkg and shp versions of the above code:

>```python
>---------------------------------------------------------------------------
>BrokenProcessPool                         Traceback (most recent call last)
>~/../some_dir/test.py in 
>      183 
>      184 
>---> 185 to_file(gdf, 'test.gpkg')
>      186 # to_file(gdf, 'test.shp')
>
>~/../some_dir/test.py in to_file(df, path, driver, parallel, compute, **kwargs)
>      178 
>      179     if compute:
>---> 180         dask.compute(result, scheduler="processes")
>      181     else:
>      182         return result
>
>~/opt/anaconda3/envs/geo-tools/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
>     566         postcomputes.append(x.__dask_postcompute__())
>     567 
>--> 568     results = schedule(dsk, keys, **kwargs)
>     569     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
>     570 
>
>~/opt/anaconda3/envs/geo-tools/lib/python3.7/site-packages/dask/multiprocessing.py in get(dsk, keys, num_workers, func_loads, >func_dumps, optimize_graph, pool, chunksize, **kwargs)
>     228             raise_exception=reraise,
>     229             chunksize=chunksize,
>--> 230             **kwargs
>     231         )
>     232     finally:
>
>~/opt/anaconda3/envs/geo-tools/lib/python3.7/site-packages/dask/local.py in get_async(submit, num_workers, dsk, result, cache, >get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, chunksize, **kwargs)
>     501             while state["waiting"] or state["ready"] or state["running"]:
>     502                 fire_tasks(chunksize)
>--> 503                 for key, res_info, failed in queue_get(queue).result():
>     504                     if failed:
>     505                         exc, tb = loads(res_info)
>
>~/opt/anaconda3/envs/geo-tools/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
>     426                 raise CancelledError()
>     427             elif self._state == FINISHED:
>--> 428                 return self.__get_result()
>     429 
>     430             self._condition.wait(timeout)
>
>~/opt/anaconda3/envs/geo-tools/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
 >     382     def __get_result(self):
>     383         if self._exception:
>--> 384             raise self._exception
 >     385         else:
 >     386             return self._result
>
>BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
>```

<br>
I just started looking into Dask recently. It's still new to me, so I don't really get this error message and I'd like to know if there's  an "easy" fix/workaround to make the to_file function work with ESRI shapefiles?
<br>
<br>
Please let me know.
