### ISSUE TITLE
point_from_xy only gets applied to first partition

### ISSUE THREAD

**Issue by daviddemeij** [jsignell/dask-geopandas#24]
In certain situations, the `dask_geopandas.points_from_xy` only gets applied to the first partition. I am not sure when this happens exactly as I also had cases when this error didn't seem to occur. But below I have a minimal example that causes this problem. 

```
import pandas as pd
import dask_geopandas
import dask.dataframe as dd
import numpy as np

N = 9
df = pd.DataFrame({'x': np.random.randn(N), 'y': np.random.randn(N)})
ddf = dd.from_pandas(df, npartitions=3)
ddf["geometry"] = dask_geopandas.points_from_xy(ddf, "x", "y")
ddf = dask_geopandas.from_dask_dataframe(ddf)
ddf.compute()
```

![image](https://user-images.githubusercontent.com/19728972/95065930-fca58600-0701-11eb-8f0f-145de06ee9f3.png)

**Comment by daviddemeij** [comment]
I found a clue that might explain why this is happening, it seems that the index returned by `dask_geopandas.points_from_xy` is per partition. Am I using this function in the wrong way?
![image](https://user-images.githubusercontent.com/19728972/95067963-df25eb80-0704-11eb-9f8b-9ce8d947791e.png)

**Comment by daviddemeij** [comment]
Found a simple solution, by manually updating the index of the resulting points:
![image](https://user-images.githubusercontent.com/19728972/95073741-a50d1780-070d-11eb-826f-50ba0be63f38.png)

**Comment by jorisvandenbossche** [comment]
@daviddemeij Thanks a lot for the report!

It was indeed the index that was not correctly set in the return value of `points_from_xy` (but it seems to depend on the exact number of elements in the partitions if this gives a problem or not)

Fix in https://github.com/jsignell/dask-geopandas/pull/26
